// Chữ trên trang web. Tiếng Việt là bản chính, tiếng Anh là bản dịch đầy đủ.

export const S = {
  vi: {
    lang: 'vi',
    other: 'en',
    otherName: 'English',
    siteName: 'BK Study Library',
    siteTag: 'Thư viện tài liệu do sinh viên Bách Khoa TP.HCM soạn và chia sẻ',
    unofficial: 'Dự án của sinh viên, không phải trang chính thức của Trường Đại học Bách khoa - ĐHQG-HCM.',
    skip: 'Bỏ qua, tới nội dung',
    nav: { home: 'Trang chủ', contribute: 'Đóng góp', review: 'Duyệt bài', takedown: 'Gỡ tài liệu', github: 'GitHub' },
    homeTitle: 'Thư viện tài liệu theo môn',
    homeIntro:
      'Tóm tắt, ghi chú, mẫu prelab, gói quiz do sinh viên tự soạn, cùng link tới tài liệu mở trên mạng. Mọi thứ xếp theo mã môn, đọc được ngay trên trình duyệt, không cần cài app.',
    homeRules:
      'Thư viện chỉ nhận tài liệu bạn tự soạn và link tới nguồn công khai. Không đăng slide của giảng viên hay đề thi khi chưa được phép.',
    searchLabel: 'Tìm môn theo mã hoặc tên',
    searchPlaceholder: 'Ví dụ: MT1005, giai tich, mach dien',
    searchHint: 'Gõ không dấu cũng được. Tìm cả mã môn cũ.',
    searchNoJs: 'Ô tìm kiếm cần JavaScript. Bạn vẫn xem được danh sách khoa bên dưới.',
    results: (n) => (n ? `${n} môn khớp` : 'Không có môn nào khớp'),
    resultsMore: (n) => `Hiện 30 môn đầu, còn ${n} môn nữa. Gõ thêm để thu hẹp.`,
    browseFaculty: 'Xem theo khoa',
    programsTitle: 'Chương trình đào tạo',
    noPrograms: 'Chưa có chương trình nào trong danh mục.',
    coursesCount: (n) => `${n} môn`,
    itemsCount: (n) => `${n} tài liệu`,
    stats: (c, i) => `${c} môn, ${i} tài liệu`,
    contributeCta: 'Bạn có tóm tắt, ghi chú hay mẫu prelab tự soạn? Gửi qua form, không cần biết Git.',
    contributeBtn: 'Đóng góp tài liệu',
    reviewCta: 'Muốn duyệt tài liệu cho môn bạn giỏi?',
    reviewBtn: 'Xem cách duyệt',
    faculty: 'Khoa',
    program: 'Chương trình',
    course: 'Môn',
    code: 'Mã môn',
    name: 'Tên môn',
    credits: 'Tín chỉ',
    status: 'Trạng thái',
    parts: 'Phần',
    partsNone: 'chưa ghi',
    aliases: 'Mã, tên cũ',
    aliasRange: (a) => [a.from, a.to].filter(Boolean).join(' đến '),
    related: 'Môn liên quan',
    replacedBy: 'Thay bằng',
    replaces: 'Thay cho',
    retiredNotice: 'Môn này đã ngừng dạy. Tài liệu cũ vẫn được giữ để link cũ không hỏng.',
    retiredSee: 'Xem môn thay thế',
    programsOfCourse: 'Thuộc chương trình',
    block: 'Khối',
    required: 'bắt buộc',
    elective: 'tự chọn',
    blockCredits: (n) => `cần ${n} tín chỉ`,
    facultyCourses: 'Môn của khoa',
    facultyPrograms: 'Chương trình của khoa',
    noCourses: 'Chưa có môn nào.',
    noItems: 'Môn này chưa có tài liệu. Bạn có thể là người đầu tiên.',
    materials: 'Tài liệu',
    example: 'Ví dụ',
    removed: 'Đã gỡ',
    anonymous: 'Ẩn danh',
    openLink: 'Mở link',
    pending: 'Đang chờ tải lên',
    prelabRefNote: 'Chỉ để tham khảo sau khi đã hết hạn chấm. Không chép để nộp.',
    term: 'Học kỳ',
    labNo: (n) => `Bài ${n}`,
    license: 'Giấy phép',
    source: 'Nguồn',
    contributeHere: 'Đóng góp cho môn này',
    addDoc: 'Gửi tài liệu',
    uploadTitle: 'Gửi tài liệu',
    uploadClosed: 'Form gửi tài liệu chưa mở.',
    // Thông báo của upload.js. Chữ có số (đuôi file, kích thước) được dựng lúc build từ policy.json.
    uploadMsg: {
      course: 'Chưa chọn môn. Gõ mã hoặc tên môn rồi chọn một môn trong danh sách.',
      type: 'Chưa chọn loại tài liệu. Chọn một loại trong danh sách.',
      title: 'Chưa có tiêu đề. Nhập tiêu đề cho tài liệu.',
      file: 'Chưa có file. Chọn file cần gửi.',
      fileEmpty: 'File rỗng. Chọn file khác.',
      fileExt: (list) => `Không nhận đuôi file này. Dùng một trong: ${list}.`,
      fileSize: (max) => `File quá lớn. Chọn file nhỏ hơn ${max}.`,
      book: 'Chưa có tên sách hoặc tác giả. Nhập tên sách và ít nhất một tác giả.',
      confirm: 'Chưa đủ xác nhận. Đánh dấu cả ba ô cam kết.',
      busy: 'Đang gửi.',
      send: 'Gửi tài liệu',
      failed: 'Chưa gửi được. Thử lại sau ít phút.',
      done: 'Đã nhận tài liệu. Mã bài của bạn là',
      waiting: 'File đang chờ người duyệt xem.',
      selected: 'Đã chọn',
      noMatch: 'Không có môn nào khớp.',
      loadFail: 'Không tải được danh sách môn. Tải lại trang để thử lại.',
    },
    addLink: 'Thêm link',
    fixCatalog: 'Sửa thông tin môn',
    viewOnGithub: 'Xem trên GitHub',
    breadcrumb: 'Đường dẫn',
    footerLicense:
      'Nội dung theo CC BY-SA 4.0 trừ khi ghi khác; link giữ giấy phép của nguồn. Mã nguồn (scripts/) theo MIT.',
    footerPrivacy: 'Trang không dùng cookie, không theo dõi, không quảng cáo.',
    footerUpdated: (d) => `Cập nhật dữ liệu: ${d}`,
    notFoundTitle: 'Không tìm thấy trang',
    notFoundText: 'Trang này không có hoặc đã đổi địa chỉ. Địa chỉ môn dùng ID cố định, nên link tới môn không bị hỏng khi môn đổi tên.',
    backHome: 'Về trang chủ',
    redirecting: 'Đang chuyển tới',
  },
  en: {
    lang: 'en',
    other: 'vi',
    otherName: 'Tiếng Việt',
    siteName: 'BK Study Library',
    siteTag: 'A study library written and shared by HCMUT students',
    unofficial: 'A student project, not an official site of Ho Chi Minh City University of Technology (HCMUT).',
    skip: 'Skip to content',
    nav: { home: 'Home', contribute: 'Contribute', review: 'Review', takedown: 'Takedown', github: 'GitHub' },
    homeTitle: 'Study materials by course',
    homeIntro:
      'Summaries, notes, prelab templates and quiz packs written by students, plus links to open resources on the web. Everything is sorted by course code and works in the browser, with no app to install.',
    homeRules:
      'The library accepts only material you wrote yourself and links to public sources. Lecturer slides and exam papers are not accepted without permission.',
    searchLabel: 'Search courses by code or name',
    searchPlaceholder: 'For example: MT1005, giai tich, circuits',
    searchHint: 'Vietnamese without diacritics works too. Old course codes are included.',
    searchNoJs: 'Search needs JavaScript. You can still browse the faculties below.',
    results: (n) => (n ? `${n} matching ${n === 1 ? 'course' : 'courses'}` : 'No matching courses'),
    resultsMore: (n) => `Showing the first 30; ${n} more. Type more to narrow down.`,
    browseFaculty: 'Browse by faculty',
    programsTitle: 'Programs',
    noPrograms: 'No programs in the catalog yet.',
    coursesCount: (n) => `${n} ${n === 1 ? 'course' : 'courses'}`,
    itemsCount: (n) => `${n} ${n === 1 ? 'item' : 'items'}`,
    stats: (c, i) => `${c} courses, ${i} items`,
    contributeCta: 'Have a summary, notes or a prelab template you wrote? Send it with a form; no Git needed.',
    contributeBtn: 'Contribute material',
    reviewCta: 'Want to review material for a course you know well?',
    reviewBtn: 'How reviewing works',
    faculty: 'Faculty',
    program: 'Program',
    course: 'Course',
    code: 'Code',
    name: 'Name',
    credits: 'Credits',
    status: 'Status',
    parts: 'Parts',
    partsNone: 'not recorded',
    aliases: 'Old codes and names',
    aliasRange: (a) => [a.from, a.to].filter(Boolean).join(' to '),
    related: 'Related courses',
    replacedBy: 'Replaced by',
    replaces: 'Replaces',
    retiredNotice: 'This course is no longer taught. Its material stays here so that old links keep working.',
    retiredSee: 'See the replacement course',
    programsOfCourse: 'In programs',
    block: 'Block',
    required: 'required',
    elective: 'elective',
    blockCredits: (n) => `${n} credits needed`,
    facultyCourses: 'Courses',
    facultyPrograms: 'Programs',
    noCourses: 'No courses yet.',
    noItems: 'This course has no material yet. You can be the first to add some.',
    materials: 'Material',
    example: 'Example',
    removed: 'Removed',
    anonymous: 'Anonymous',
    openLink: 'Open link',
    pending: 'Waiting for upload',
    prelabRefNote: 'For reference only, after grading has closed. Do not copy it for submission.',
    term: 'Term',
    labNo: (n) => `Lab ${n}`,
    license: 'License',
    source: 'Source',
    contributeHere: 'Contribute to this course',
    addDoc: 'Send material',
    addLink: 'Add a link',
    fixCatalog: 'Fix course details',
    viewOnGithub: 'View on GitHub',
    breadcrumb: 'Breadcrumb',
    footerLicense:
      'Content is under CC BY-SA 4.0 unless marked otherwise; links keep the license of their source. Code (scripts/) is under MIT.',
    footerPrivacy: 'This site uses no cookies, no tracking and no ads.',
    footerUpdated: (d) => `Data updated: ${d}`,
    notFoundTitle: 'Page not found',
    notFoundText: 'This page does not exist or has moved. Course addresses use a fixed ID, so links to a course keep working after it is renamed.',
    backHome: 'Go to the home page',
    redirecting: 'Redirecting to',
  },
};
