// Chữ trên trang web. Tiếng Việt là bản chính, tiếng Anh là bản dịch đầy đủ.
// Văn phong: câu ngắn, gọi "bạn", viết hoa chữ đầu câu. Cùng một thứ thì cùng một từ:
// "tài liệu" (không dùng "mục"), "chương trình đào tạo" khi nói về văn bản của trường, "chương trình" trong danh sách.

import { EXAM_KINDS } from './labels.mjs';

export const S = {
  vi: {
    lang: 'vi',
    other: 'en',
    otherName: 'English',
    siteName: 'BK Study Library',
    siteTag: 'Tài liệu học tập do sinh viên Bách Khoa TP.HCM chia sẻ',
    unofficial: 'Dự án của sinh viên, không phải trang chính thức của Trường Đại học Bách khoa - ĐHQG-HCM.',
    skip: 'Tới nội dung chính',
    nav: { home: 'Trang chủ', send: 'Gửi tài liệu', contribute: 'Đóng góp', review: 'Duyệt bài', takedown: 'Gỡ tài liệu', github: 'GitHub' },
    homeTitle: 'Thư viện tài liệu theo môn',
    homeIntro: 'Tài liệu do sinh viên Bách Khoa chia sẻ, xếp theo mã môn. Mở là đọc được, không cần cài app.',
    homeRules: 'Thư viện nhận mọi tài liệu học tập, trừ file sách có bản quyền. Sách thì chỉ ghi tên.',
    searchLabel: 'Tìm môn, ngành hoặc tài liệu',
    searchPlaceholder: 'Ví dụ: giai tich 2, mach dien, cuoi ky HK241',
    searchHint: 'Nên tìm theo tên môn, vì mã môn có thể đổi qua các khóa. Gõ không dấu cũng được, tìm được cả mã cũ, tên giảng viên, học kỳ như HK241.',
    facultyFilter: 'Khoa',
    allFaculties: 'Tất cả khoa',
    docsTitle: 'Tài liệu',
    recentTitle: 'Tài liệu mới',
    docType: 'Loại tài liệu',
    docTypeAll: 'Mọi loại',
    docTerm: 'Học kỳ',
    docTermAll: 'Mọi học kỳ',
    docKind: 'Kỳ thi',
    docKindAll: 'Mọi kỳ thi',
    docCount: ['Không có tài liệu nào khớp.', '1 tài liệu khớp', '{n} tài liệu khớp'],
    docMore: 'Còn {n} tài liệu nữa. Gõ thêm hoặc chọn bộ lọc để thu hẹp.',
    chapter: 'Chương',
    examKinds: EXAM_KINDS,
    courseDescription: (code, name, n) => (n ? `${code} ${name}: ${n} tài liệu do sinh viên Bách Khoa chia sẻ.` : `${code} ${name}: chưa có tài liệu.`),
    facultyDescription: (name, c, p) => (c || p ? `${name}: ${c} môn, ${p} chương trình và tài liệu do sinh viên chia sẻ.` : `${name}: chưa có môn hay chương trình.`),
    programDescription: (name, n) => (n ? `Chương trình ${name}: ${n} môn theo khối và tài liệu do sinh viên chia sẻ.` : `Chương trình ${name}: chưa có danh sách môn.`),
    socialImageAlt: 'BK Study Library, thư viện tài liệu học tập theo mã môn',
    teacher: 'Giảng viên',
    teachersOfCourse: 'Giảng viên có tài liệu',
    searchNoJs: 'Ô tìm cần bật JavaScript. Danh sách khoa ở ngay bên dưới.',
    results: (n) => (n ? `${n} môn khớp` : 'Không có môn nào khớp'),
    browseFaculty: 'Xem theo khoa',
    programsTitle: 'Chương trình đào tạo',
    programsCount: (n) => `${n} chương trình`,
    noData: 'Chưa có môn',
    facultyEmpty: 'Khoa này chưa có môn hay chương trình nào.',
    facultyNoPrograms: 'Chưa có chương trình nào. Gửi chương trình đào tạo của khóa bạn để thêm vào.',
    facultyUnknownNote: 'Môn có mã chưa rõ thuộc khoa nào. Biết đúng khoa thì báo qua form Sửa thông tin môn.',
    programNoCourses: 'Chưa có danh sách môn. Gửi chương trình đào tạo của khóa bạn để thêm vào.',
    programNoCoursesShort: 'chưa có danh sách môn',
    addProgram: 'Thêm chương trình đào tạo',
    cohort: (y) => `Khóa ${y}`,
    cohortUnknown: 'Chưa rõ khóa',
    noMaterial: 'chưa có',
    programSource: 'Nguồn chính thức',
    programCtdtPdf: 'PDF chương trình đào tạo',
    programPlanPdf: 'PDF kế hoạch giảng dạy',
    programPdfHosted: 'PDF nằm trên trang của trường, thư viện chỉ dẫn link.',
    programTable: 'Danh sách chương trình của trường',
    programDraft: 'Đây là bản nháp, không hiện trong danh sách. Môn và tên khối có thể chưa khớp bản chính thức.',
    programDraftSee: 'Xem bản chính',
    programDraftTag: 'bản nháp',
    facultySharedNote: 'Môn và điều kiện tốt nghiệp chung cho mọi ngành. Chưa rõ đơn vị nào quản lý.',
    programCode: (code) => `Mã ${code}`,
    majorsCount: (n) => `${n} ngành`,
    facultyMajors: 'Ngành của khoa',
    otherPrograms: 'Chương trình khác',
    emptyPrograms: (n) => `${n} chương trình chưa có danh sách môn`,
    cohortsLabel: 'Khóa',
    majorNoCourses: 'chưa có danh sách môn',
    majorCode: (code) => `Mã ngành ${code}`,
    majorDescription: (name) => `Ngành ${name}: lộ trình theo học kỳ và tài liệu do sinh viên chia sẻ.`,
    majorLink: 'Ngành',
    pickersLabel: 'Chọn chương trình',
    pickType: 'Loại chương trình',
    pickCohort: 'Khóa',
    programsOfMajor: 'Chương trình theo khóa',
    roadmapTitle: 'Lộ trình theo học kỳ',
    roadmapOf: (label) => `Theo chương trình ${label}. Học kỳ lấy từ kế hoạch giảng dạy của trường, chỉ để tham khảo.`,
    roadmapNone: 'Chương trình này chưa có học kỳ đề xuất. Danh sách môn theo khối nằm ở trang chương trình.',
    roadmapOpen: 'Xem đủ khối kiến thức',
    semester: (n) => `Học kỳ ${n}`,
    noSemester: 'Chưa có học kỳ đề xuất',
    blocksTitle: 'Khối kiến thức',
    blocksOf: (label) => `Theo chương trình ${label}.`,
    postgradTitle: 'Sau đại học',
    postgradIntro: 'Ngành thạc sĩ, tiến sĩ theo chương trình đào tạo chính thức của trường.',
    postgradStats: (master, doctor, programs) => `${master} ngành thạc sĩ, ${doctor} ngành tiến sĩ, ${programs} chương trình`,
    postgradCourses: 'Môn sau đại học',
    postgradCoursesNote: 'Môn chỉ có ở chương trình thạc sĩ, tiến sĩ.',
    programNoCodes: 'Chương trình đào tạo của khóa này không ghi mã môn. Xem danh sách môn trong PDF của trường.',
    programNoCodesShort: 'chưa có danh sách mã môn',
    levelName: (level, name) => `${level} ${name}`,
    levelLabel: 'Bậc',
    majorDescriptionPg: (name) => `${name}: chương trình theo khóa và khối kiến thức theo bản chính thức của trường.`,
    totalCredits: (n) => `${n} tín chỉ`,
    coursesNeed: (n) => `chọn ${n} môn`,
    handbookMajor: 'Xem ngành trên Sổ tay HCMUT',
    handbookCourse: 'Trang môn trên Sổ tay HCMUT',
    handbook: 'Sổ tay HCMUT',
    facultySharedCourses: 'Môn chung khoa dùng',
    facultySharedCoursesNote: 'Danh sách đủ ở trang',
    facultyEmptyShared: 'Môn chung của mọi ngành nằm ở trang',
    contributeGuide: 'Hướng dẫn đóng góp',
    coursesCount: (n) => `${n} môn`,
    itemsCount: (n) => `${n} tài liệu`,
    stats: (c, i) => `${c} môn, ${i} tài liệu`,
    contributeCta: 'Có tài liệu muốn chia sẻ? Gửi qua form, không cần tài khoản GitHub.',
    contributeBtn: 'Gửi tài liệu',
    moreItems: (n) => `Xem thêm ${n} tài liệu`,
    reviewCta: 'Muốn duyệt tài liệu cho môn bạn giỏi?',
    reviewBtn: 'Xem cách duyệt',
    faculty: 'Khoa',
    code: 'Mã môn',
    name: 'Tên môn',
    credits: 'Tín chỉ',
    status: 'Trạng thái',
    parts: 'Phần',
    partsNone: 'chưa ghi',
    aliases: 'Mã, tên cũ',
    aliasRange: (a) => [a.from, a.to].filter(Boolean).join(' đến '),
    related: 'Môn liên quan',
    replacedBy: 'Thay bằng',
    replaces: 'Thay cho',
    retiredNotice: 'Môn này đã ngừng dạy. Tài liệu cũ vẫn giữ lại.',
    retiredSee: 'Xem môn thay thế',
    programsOfCourse: 'Thuộc chương trình',
    required: 'bắt buộc',
    elective: 'tự chọn',
    blockCredits: (n) => `cần ${n} tín chỉ`,
    facultyCourses: 'Môn của khoa',
    facultyPrograms: 'Chương trình của khoa',
    noCourses: 'Chưa có môn nào.',
    noItems: 'Chưa có tài liệu cho môn này.',
    materials: 'Tài liệu',
    example: 'Ví dụ',
    removed: 'Đã gỡ',
    anonymous: 'Ẩn danh',
    openLink: 'Mở link',
    preview: 'Xem trước',
    previewNamed: (name) => `Xem trước ${name}`,
    download: (size) => `Tải xuống (${size})`,
    downloadNamed: (name, size) => `Tải xuống ${name} (${size})`,
    requestTakedown: 'Yêu cầu gỡ',
    pendingFile: (name) => `${name}: đang chờ tải lên.`,
    prelabRefNote: 'Chỉ để tham khảo sau khi đã hết hạn chấm. Không chép để nộp.',
    term: 'Học kỳ',
    labNo: (n) => `Bài ${n}`,
    license: 'Giấy phép',
    source: 'Nguồn',
    contributeHere: 'Đóng góp cho môn này',
    addDoc: 'Gửi tài liệu',
    uploadTitle: 'Gửi tài liệu',
    uploadClosed: 'Form gửi tài liệu chưa mở.',
    uploadExtOnly: (ext, types) => `File ${ext} chỉ dùng cho ${types}.`,
    // Thông báo của upload.js. Chữ có số (đuôi file, kích thước) được dựng lúc build từ policy.json.
    uploadMsg: {
      course: 'Chưa chọn môn. Gõ mã hoặc tên môn rồi chọn trong danh sách.',
      type: 'Chưa chọn loại tài liệu.',
      title: 'Chưa có tiêu đề.',
      file: 'Chưa chọn file.',
      fileEmpty: 'File rỗng. Chọn file khác.',
      fileExt: (list) => `Không nhận đuôi file này. Dùng một trong: ${list}.`,
      fileExtType: 'Loại tài liệu này không nhận đuôi file đó. Dùng một trong:',
      fileSize: (max) => `File quá lớn. Chọn file nhỏ hơn ${max}.`,
      book: 'Cần tên sách và ít nhất một tác giả.',
      confirm: 'Đánh dấu cả ba ô xác nhận.',
      busy: 'Đang gửi.',
      send: 'Gửi tài liệu',
      failed: 'Chưa gửi được. Thử lại sau ít phút.',
      done: 'Đã nhận tài liệu. Mã bài của bạn là',
      waiting: 'File đang chờ người duyệt xem.',
      viewLink: 'Link xem bài của bạn',
      viewSave: 'Lưu lại link này: thư viện không gửi lại được. Link là bí mật, đừng chia sẻ.',
      selected: 'Đã chọn',
      noMatch: 'Không có môn nào khớp.',
      loadFail: 'Không tải được danh sách môn. Tải lại trang để thử lại.',
    },
    addLink: 'Thêm link',
    fixCatalog: 'Sửa thông tin môn',
    viewOnGithub: 'Xem trên GitHub',
    breadcrumb: 'Đường dẫn',
    footerLicense: 'Nội dung theo CC BY-SA 4.0 trừ khi ghi khác; link giữ giấy phép của nguồn. Mã nguồn (scripts/) theo MIT.',
    footerPrivacy: 'Không cookie, không theo dõi, không quảng cáo. Riêng trang Gửi tài liệu dùng Turnstile của Cloudflare để chặn bot.',
    footerUpdated: (d) => `Cập nhật dữ liệu: ${d}`,
    notFoundTitle: 'Không tìm thấy trang',
    notFoundText: 'Trang này không có hoặc đã đổi địa chỉ. Thử tìm môn ở trang chủ.',
    backHome: 'Về trang chủ',
    redirecting: 'Đang chuyển tới',
    // Môn trùng tên: ngữ cảnh ngắn (scripts/lib/course-context.mjs) và ghi chú trên trang môn.
    contextMore: (first, n) => `${first} và ${n} ngành khác`,
    contextCohorts: (years) => `khóa ${years}`,
    yearRange: (a, b) => `${a} đến ${b}`,
    sameName: (n) => `Tên này còn dùng cho ${n} môn khác.`,
    sameNameLink: 'Xem các môn cùng tên',
  },
  en: {
    lang: 'en',
    other: 'vi',
    otherName: 'Tiếng Việt',
    siteName: 'BK Study Library',
    siteTag: 'Study material shared by HCMUT students',
    unofficial: 'A student project, not an official site of Ho Chi Minh City University of Technology (HCMUT).',
    skip: 'Skip to main content',
    nav: { home: 'Home', send: 'Send material', contribute: 'Contribute', review: 'Review', takedown: 'Takedown', github: 'GitHub' },
    homeTitle: 'Study material by course',
    homeIntro: 'Material shared by HCMUT students, sorted by course code. It opens in the browser, no app needed.',
    homeRules: 'The library takes any study material except copyrighted book files. Books are listed by title only.',
    searchLabel: 'Search courses, majors or material',
    searchPlaceholder: 'For example: giai tich 2, circuits, final HK241',
    searchHint: 'Search by course name first: course codes can change between intakes. Vietnamese without diacritics works, and so do old codes, lecturer names and terms like HK241.',
    facultyFilter: 'Faculty',
    allFaculties: 'All faculties',
    docsTitle: 'Material',
    recentTitle: 'New material',
    docType: 'Material type',
    docTypeAll: 'All types',
    docTerm: 'Term',
    docTermAll: 'All terms',
    docKind: 'Exam',
    docKindAll: 'All exams',
    docCount: ['No matching material.', '1 matching item', '{n} matching items'],
    docMore: '{n} more. Type more or use a filter to narrow down.',
    chapter: 'Chapter',
    examKinds: { gk: 'Midterm', ck: 'Final', quiz: 'Quiz', kt: 'Test' },
    courseDescription: (code, name, n) => (n ? `${code} ${name}: ${n} ${n === 1 ? 'item' : 'items'} shared by HCMUT students.` : `${code} ${name}: no material yet.`),
    facultyDescription: (name, c, p) => (c || p ? `${name}: ${c} ${c === 1 ? 'course' : 'courses'}, ${p} ${p === 1 ? 'program' : 'programs'} and material shared by students.` : `${name}: no courses or programs yet.`),
    programDescription: (name, n) => (n ? `${name}: ${n} ${n === 1 ? 'course' : 'courses'} by block and material shared by students.` : `${name}: no course list yet.`),
    socialImageAlt: 'BK Study Library, a study library organized by course code',
    teacher: 'Lecturer',
    teachersOfCourse: 'Lecturers with materials',
    searchNoJs: 'Search needs JavaScript. The faculty list is right below.',
    results: (n) => (n ? `${n} matching ${n === 1 ? 'course' : 'courses'}` : 'No matching courses'),
    browseFaculty: 'Browse by faculty',
    programsTitle: 'Programs',
    programsCount: (n) => `${n} ${n === 1 ? 'program' : 'programs'}`,
    noData: 'No courses yet',
    facultyEmpty: 'This faculty has no courses or programs yet.',
    facultyNoPrograms: 'No programs yet. Send the curriculum of your cohort to add one (form in Vietnamese).',
    facultyUnknownNote: 'These course codes are not matched to a faculty yet. If you know the faculty, report it with the Fix course details form.',
    programNoCourses: 'No course list yet. Send the curriculum of your cohort to add it (form in Vietnamese).',
    programNoCoursesShort: 'no course list yet',
    addProgram: 'Add a program',
    cohort: (y) => `Cohort ${y}`,
    cohortUnknown: 'Cohort not stated',
    noMaterial: 'none yet',
    programSource: 'Official source',
    programCtdtPdf: 'Curriculum PDF',
    programPlanPdf: 'Teaching plan PDF',
    programPdfHosted: 'The PDFs are on the university site; the library only links to them.',
    programTable: 'University program list',
    programDraft: 'This is a draft and is not listed. Its courses and block names may not match the official version.',
    programDraftSee: 'See the main version',
    programDraftTag: 'draft',
    facultySharedNote: 'Courses and graduation requirements shared by every major. The managing unit is not known yet.',
    programCode: (code) => `Code ${code}`,
    majorsCount: (n) => `${n} ${n === 1 ? 'major' : 'majors'}`,
    facultyMajors: 'Majors',
    otherPrograms: 'Other programs',
    emptyPrograms: (n) => `${n} ${n === 1 ? 'program' : 'programs'} without a course list yet`,
    cohortsLabel: 'Cohorts',
    majorNoCourses: 'no course list yet',
    majorCode: (code) => `Major code ${code}`,
    majorDescription: (name) => `${name}: roadmap by semester and material shared by students.`,
    majorLink: 'Major',
    pickersLabel: 'Pick a program',
    pickType: 'Program type',
    pickCohort: 'Cohort',
    programsOfMajor: 'Programs by cohort',
    roadmapTitle: 'Roadmap by semester',
    roadmapOf: (label) => `Based on the ${label} program. Semesters come from the university teaching plan and are only a guide.`,
    roadmapNone: 'This program has no recommended semesters yet. The course list by block is on the program page.',
    roadmapOpen: 'See all knowledge blocks',
    semester: (n) => `Semester ${n}`,
    noSemester: 'No recommended semester',
    blocksTitle: 'Knowledge blocks',
    blocksOf: (label) => `Based on the ${label} program.`,
    postgradTitle: 'Postgraduate',
    postgradIntro: "Master's and doctoral majors from the official university curricula.",
    postgradStats: (master, doctor, programs) => `${master} master's ${master === 1 ? 'major' : 'majors'}, ${doctor} doctoral ${doctor === 1 ? 'major' : 'majors'}, ${programs} ${programs === 1 ? 'program' : 'programs'}`,
    postgradCourses: 'Postgraduate courses',
    postgradCoursesNote: "Courses that only appear in master's and doctoral programs.",
    programNoCodes: 'The curriculum of this cohort lists no course codes. See the course list in the university PDF.',
    programNoCodesShort: 'no course codes yet',
    levelName: (level, name) => `${name} (${level})`,
    levelLabel: 'Level',
    majorDescriptionPg: (name) => `${name}: programs by cohort and knowledge blocks from the official curriculum.`,
    totalCredits: (n) => `${n} ${n === 1 ? 'credit' : 'credits'}`,
    coursesNeed: (n) => `pick ${n} ${n === 1 ? 'course' : 'courses'}`,
    handbookMajor: 'View the major on the HCMUT handbook',
    handbookCourse: 'Course page on the HCMUT handbook',
    handbook: 'HCMUT handbook',
    facultySharedCourses: 'Shared courses used here',
    facultySharedCoursesNote: 'The full list is on',
    facultyEmptyShared: 'Courses every major takes are on',
    contributeGuide: 'Contribution guide',
    coursesCount: (n) => `${n} ${n === 1 ? 'course' : 'courses'}`,
    itemsCount: (n) => `${n} ${n === 1 ? 'item' : 'items'}`,
    stats: (c, i) => `${c} courses, ${i} items`,
    contributeCta: 'Have material to share? Send it with a form (in Vietnamese), no GitHub account needed.',
    contributeBtn: 'Send material',
    moreItems: (n) => `Show ${n} more`,
    reviewCta: 'Want to review material for a course you know well?',
    reviewBtn: 'How reviewing works',
    faculty: 'Faculty',
    code: 'Code',
    name: 'Name',
    credits: 'Credits',
    status: 'Status',
    parts: 'Parts',
    partsNone: 'not recorded',
    aliases: 'Old codes and names',
    aliasRange: (a) => [a.from, a.to].filter(Boolean).join(' to '),
    related: 'Related courses',
    replacedBy: 'Replaced by',
    replaces: 'Replaces',
    retiredNotice: 'This course is no longer taught. Its old material stays here.',
    retiredSee: 'See the replacement course',
    programsOfCourse: 'In programs',
    required: 'required',
    elective: 'elective',
    blockCredits: (n) => `${n} credits needed`,
    facultyCourses: 'Courses',
    facultyPrograms: 'Programs',
    noCourses: 'No courses yet.',
    noItems: 'No material for this course yet.',
    materials: 'Material',
    example: 'Example',
    removed: 'Removed',
    anonymous: 'Anonymous',
    openLink: 'Open link',
    preview: 'Preview',
    previewNamed: (name) => `Preview ${name}`,
    download: (size) => `Download (${size})`,
    downloadNamed: (name, size) => `Download ${name} (${size})`,
    requestTakedown: 'Request removal',
    pendingFile: (name) => `${name}: waiting for upload.`,
    prelabRefNote: 'For reference only, after grading has closed. Do not copy it for submission.',
    term: 'Term',
    labNo: (n) => `Lab ${n}`,
    license: 'License',
    source: 'Source',
    contributeHere: 'Contribute to this course',
    addDoc: 'Send material',
    addLink: 'Add a link',
    fixCatalog: 'Fix course details',
    viewOnGithub: 'View on GitHub',
    breadcrumb: 'Breadcrumb',
    footerLicense: 'Content is under CC BY-SA 4.0 unless marked otherwise; links keep the license of their source. Code (scripts/) is under MIT.',
    footerPrivacy: 'No cookies, no tracking, no ads. Only the Gửi tài liệu (submit) page uses Cloudflare Turnstile to block bots.',
    footerUpdated: (d) => `Data updated: ${d}`,
    notFoundTitle: 'Page not found',
    notFoundText: 'This page does not exist or has moved. Try searching for the course on the home page.',
    backHome: 'Go to the home page',
    redirecting: 'Redirecting to',
    contextMore: (first, n) => `${first} and ${n} more ${n === 1 ? 'major' : 'majors'}`,
    contextCohorts: (years) => `${/[ ,]/.test(years) ? 'cohorts' : 'cohort'} ${years}`,
    yearRange: (a, b) => `${a} to ${b}`,
    sameName: (n) => `${n} other ${n === 1 ? 'course has' : 'courses have'} the same name.`,
    sameNameLink: 'See courses with this name',
  },
};
